export const POPULAR_CITIES = [
  'Agra', 'Ahmedabad', 'Ajmer', 'Amritsar', 'Aurangabad',
  'Bangalore', 'Bhopal', 'Bhubaneswar', 'Chandigarh', 'Chennai',
  'Coimbatore', 'Delhi', 'Dehradun', 'Goa', 'Guwahati',
  'Hyderabad', 'Indore', 'Jaipur', 'Jodhpur', 'Kanpur',
  'Kochi', 'Kolkata', 'Lucknow', 'Ludhiana', 'Madurai',
  'Mangalore', 'Mumbai', 'Mysore', 'Nagpur', 'Nashik',
  'Patna', 'Pune', 'Raipur', 'Surat', 'Thiruvananthapuram',
  'Udaipur', 'Vadodara', 'Varanasi', 'Vijayawada', 'Visakhapatnam',
]

export const MOCK_BUSES = [
  {
    name: 'MadBus Express',
    type: 'AC Sleeper',
    departs: '22:00',
    arrives: '06:00',
    duration: '8h 00m',
    fromStop: 'Dadar Bus Terminal',
    toStop: 'Majestic Bus Stand',
    seats: 8,
    price: 799,
    rating: 4.7,
    amenities: ['AC', 'WiFi', 'Charging'],
  },
  {
    name: 'Swift Travels',
    type: 'Non-AC Semi-Sleeper',
    departs: '20:30',
    arrives: '04:30',
    duration: '8h 00m',
    fromStop: 'Sion Bus Depot',
    toStop: 'Shivajinagar',
    seats: 24,
    price: 399,
    rating: 4.2,
    amenities: ['Charging'],
  },
  {
    name: 'Royal Volvo Coach',
    type: 'Volvo AC Sleeper',
    departs: '21:30',
    arrives: '05:30',
    duration: '8h 00m',
    fromStop: 'Kurla Terminus',
    toStop: 'Majestic Bus Stand',
    seats: 4,
    price: 999,
    rating: 4.8,
    amenities: ['AC', 'WiFi', 'Charging', 'Refreshments'],
  },
  {
    name: 'Night Rider Bus Co.',
    type: 'AC Seater',
    departs: '23:00',
    arrives: '07:30',
    duration: '8h 30m',
    fromStop: 'Dadar Bus Terminal',
    toStop: 'KSR Bus Stand',
    seats: 18,
    price: 549,
    rating: 4.4,
    amenities: ['AC', 'Charging'],
  },
  {
    name: 'City Link Travels',
    type: 'Non-AC Seater',
    departs: '19:00',
    arrives: '03:00',
    duration: '8h 00m',
    fromStop: 'Andheri East',
    toStop: 'Shivajinagar',
    seats: 32,
    price: 249,
    rating: 3.9,
    amenities: [],
  },
  {
    name: 'Karnataka Express',
    type: 'AC Sleeper',
    departs: '21:00',
    arrives: '05:00',
    duration: '8h 00m',
    fromStop: 'Dadar Bus Terminal',
    toStop: 'Majestic Bus Stand',
    seats: 12,
    price: 649,
    rating: 4.5,
    amenities: ['AC', 'WiFi'],
  },
]
